name: Test und Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Run json server  
        run: npx json-server --watch db.json --port 5000

      - name: Test app
        run: npm test --coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          files:./coverage/lcov.info